name: Push Docker Image
on:
  push:
    branches:
      - frontend
    paths-ignore: ["**.md"]
  pull_request:
    branches:
      - frontend
    paths-ignore: ["**.md"]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20,21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: current directory frontend & Install dependencies
        run : |
          npm install --force
      # # - name: Format code
      #   run: npm run format 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build ./frontend -t ${{secrets.DOCKER_USERNAME}}/pbi:frontend

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/pbi:frontend

      # - name: Deploy to Production Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USER}}
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd /application-js/e-shopging && pwd
      #       # remove the existing
      #       docker-compose down
      #       #up container
      #       docker compose up -d --build
      #       #show container process
      #       docker compose ps -a
